package com.example.securitymaster.secutiry;

public interface SecurityRoles {
    String ROLES_PREFIX= "ROLE_";
    String ROLES_ADMIN = "SUPER_ADMIN";

    String DEPARTMENTS_ADMIN = "DEPARTMENTS_ADMIN";
    String DEPARTMENTS_READ = "DEPARTMENTS_READ";
    String DEPARTMENTS_CREATE = "DEPARTMENTS_CREATE";
    String DEPARTMENTS_DELETE = "DEPARTMENTS_DELETE";

    String CUSTOMERS_ADMIN = "CUSTOMERS_ADMIN";
    String CUSTOMERS_READ = "CUSTOMERS_READ";
    String CUSTOMERS_CREATE = "CUSTOMERS_CREATE";
    String CUSTOMERS_DELETE = "CUSTOMERS_DELETE";

    String EMPLOYEES_ADMIN = "EMPLOYEES_ADMIN";
    String EMPLOYEES_READ = "EMPLOYEES_READ";
    String EMPLOYEES_CREATE = "EMPLOYEES_CREATE";
    String EMPLOYEES_DELETE = "EMPLOYEES_DELETE";

}
